export const themes = [
	{
		name: 'lightGreen',
		pixelBorderColor: 'after:bg-lightGreen1',
		borderColor: 'border-lightGreen1',
		primaryBackgroundColor: 'bg-lightGreen1/25',
		secondaryBackgroundColor: 'bg-lowOpacity',
		vibrantBackgroundColor: 'bg-lightGreen1',
		gradientFrom: 'from-lightGreen2',
		gradientTo: 'to-lightGreen1',
	},
	{
		name: 'darkGreen1',
		pixelBorderColor: 'after:bg-darkGreen1',
		borderColor: 'border-darkGreen1',
		primaryBackgroundColor: 'bg-darkGreen1/25',
		secondaryBackgroundColor: 'bg-darkLowOpacity',
		vibrantBackgroundColor: 'bg-darkGreen1',
		gradientFrom: 'from-darkGreen2',
		gradientTo: 'to-darkGreen1',
	},
	{
		name: 'lightBlue',
		pixelBorderColor: 'after:bg-lightBlue2',
		borderColor: 'border-lightBlue2',
		primaryBackgroundColor: 'bg-lightBlue2/25',
		secondaryBackgroundColor: 'bg-lowOpacity',
		vibrantBackgroundColor: 'bg-lightBlue2',
		gradientFrom: 'from-lightBlue1',
		gradientTo: 'to-lightBlue2',
	},
	{
		name: 'darkBlue',
		pixelBorderColor: 'after:bg-darkBlue1',
		borderColor: 'border-darkBlue1',
		primaryBackgroundColor: 'bg-darkBlue1/25',
		secondaryBackgroundColor: 'bg-darkLowOpacity',
		vibrantBackgroundColor: 'bg-darkBlue1',
		gradientFrom: 'from-darkBlue2',
		gradientTo: 'to-darkBlue1',
	},

	{
		name: 'lightYellow',
		pixelBorderColor: 'after:bg-lightYellow1',
		borderColor: 'border-lightYellow1',
		primaryBackgroundColor: 'bg-lightYellow1/25',
		secondaryBackgroundColor: 'bg-lowOpacity',
		vibrantBackgroundColor: 'bg-lightYellow1',
		gradientFrom: 'from-lightYellow2',
		gradientTo: 'to-lightYellow1',
	},
	{
		name: 'darkYellow',
		pixelBorderColor: 'after:bg-darkYellow1',
		borderColor: 'border-darkYellow1',
		primaryBackgroundColor: 'bg-darkYellow1/25',
		secondaryBackgroundColor: 'bg-darkLowOpacity',
		vibrantBackgroundColor: 'bg-darkYellow1',
		gradientFrom: 'from-darkYellow2',
		gradientTo: 'to-darkYellow1',
	},

	{
		name: 'basePurple',
		pixelBorderColor: 'after:bg-[#5F0A87]',
		borderColor: 'border-[#5F0A87]',
		primaryBackgroundColor: 'bg-[#5F0A87]/25',
		secondaryBackgroundColor: 'bg-darkLowOpacity',
		vibrantBackgroundColor: 'bg-[#5F0A87]',
		gradientFrom: 'from-[#A4508B]',
		gradientTo: 'to-[#5F0A87]',
	},
	{
		name: 'neutral',
		pixelBorderColor: 'after:bg-neutral1',
		borderColor: 'border-neutral1',
		primaryBackgroundColor: 'bg-neutral1/25',
		secondaryBackgroundColor: 'bg-darkLowOpacity',
		vibrantBackgroundColor: 'bg-neutral1',
		gradientFrom: 'from-neutral2',
		gradientTo: 'to-neutral1',
	},
]
